services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 4G