import Head from 'next/head';
import styles from '@/styles/home.module.scss';
import { useRef, useEffect } from 'react';
import { animateScroll as scroll } from 'react-scroll';
import { ArtificialScroll } from '@/components/artificialScroll/ArtificialScroll';
import { HomeHeader } from '@/containers/homeContainers/homeHeader/HomeHeader';
import { HomeManageProjects } from '@/containers/homeContainers/homeManageProjects/HomeManageProjects';
import { HomeManageEmployees } from '@/containers/homeContainers/homeManageEmployees/HomeManageEmployees';
import { HomePlans } from '@/containers/homeContainers/homePlans/HomePlans';
import { Footer } from '@/containers/homeContainers/footer/Footer';


export default function Home() {

  const headerRef = useRef<HTMLDivElement>(null);
  const projectsRef = useRef<HTMLDivElement>(null);
  const employeesRef = useRef<HTMLDivElement>(null);
  const pricesRef = useRef<HTMLDivElement>(null);
  const footerRef = useRef<HTMLDivElement>(null);

  const scrollToNextRef = (currentNr : number) => {    
    if(currentNr == 1) {
      scroll.scrollTo( projectsRef.current!.offsetTop , {
        smooth: true,
        duration: 500,
      });
    }else if(currentNr == 2) {
      scroll.scrollTo( employeesRef.current!.offsetTop , {
        smooth: true,
        duration: 500,
      });
    }else if(currentNr  == 3) {
      scroll.scrollTo( pricesRef.current!.offsetTop , {
        smooth: true,
        duration: 500,
      });
    }else if(currentNr  == 4) {
      scroll.scrollTo( footerRef.current!.offsetTop , {
        smooth: true,
        duration: 500,
      });

    }else if(currentNr  == 5) {
      scroll.scrollTo( headerRef.current!.offsetTop , {
        smooth: true,
        duration:0,
      });
    }
  }


  useEffect(() => {
    const options = {
      root: null, 
      rootMargin: '0px',
      threshold: 0.5, 
    };

    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
        
          const target = entry.target as HTMLDivElement;
          scroll.scrollTo(target.offsetTop, {
            smooth: true,
            duration: 500,
          });
        }
      });
    }, options);

   
    if (projectsRef.current) {
      observer.observe(projectsRef.current);
    }
    if (pricesRef.current) {
      observer.observe(pricesRef.current);
    }
    if (employeesRef.current) {
      observer.observe(employeesRef.current);
    }
    if (footerRef.current) {
      observer.observe(footerRef.current);
    }
    if (headerRef.current) {
      observer.observe(headerRef.current);
    }
    

    return () => {
      if (projectsRef.current) {
        observer.unobserve(projectsRef.current);
      }
      if (pricesRef.current) {
        observer.unobserve(pricesRef.current);
      }
      if (employeesRef.current) {
        observer.unobserve(employeesRef.current);
      }
      if (footerRef.current) {
        observer.unobserve(footerRef.current);
      }
      if (headerRef.current) {
        observer.unobserve(headerRef.current);
      }

    };
  }, []);


  return (
    <>
      <Head>
        <title>Empa - The Bussines Management Solution You Need</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon"  type="image"  href="/logo.png" />
        <meta lang='en'/>
      </Head>
      <div className={`appContainer flexColumn`}>
        <ArtificialScroll scrollToNextRef={ scrollToNextRef } />
        <HomeHeader headerRef={headerRef} projectsRef={projectsRef} pricesRef={pricesRef} />
        <main className={`${styles.mainHome} flexColumn`}>
          <HomeManageProjects projectsRef={projectsRef} />
          <HomeManageEmployees employeesRef = {employeesRef} />
          <HomePlans pricesRef={pricesRef} />
        </main>
        <Footer footerRef = {footerRef} />
      </div>
    </>
  )
}
